server {
  listen 80;

  # Proxy for the user service (auth backend)
  location /auth {
    proxy_pass http://user_service:5000;
  }

  # Proxy for the reward service (reward and farming backend)
  location /rewards {
    proxy_pass http://reward_service:5000;
  }

   # Proxy for the seed transaction service
  location /seed-transactions {
    proxy_pass http://seed_transaction_service:5001;
    # proxy_set_header Host $host;
    # proxy_set_header X-Real-IP $remote_addr;
    # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # For handling 404 errors
  location / {
    return 404;
  }
}
