name: Hyperledger Service - Test

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Hyperledger Fabric Binaries
      - name: Install Hyperledger Fabric Binaries
        run: |
          echo "Installing Hyperledger Fabric binaries..."
          curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.5.9
          export FABRIC_BIN_PATH=$(find $PWD -type d -name 'bin' | head -n 1)
          if [ -z "$FABRIC_BIN_PATH" ]; then
            echo "Error: Fabric binaries directory not found."
            exit 1
          fi
          export PATH=$FABRIC_BIN_PATH:$PATH
          echo "Fabric binaries installed successfully."
          peer version || echo "Peer command not found!"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        working-directory: back-end/hyperledger-service/asset-transfer-basic/rest-api-typescript
        run: |
          npm install

      # Step 4: Generate Environment Variables
      - name: Generate Environment Variables
        working-directory: back-end/hyperledger-service/asset-transfer-basic/rest-api-typescript
        run: |
          chmod +x ./scripts/generateEnv.sh
          npm run generateEnv

      # Step 5: Set Up Hyperledger Fabric Network
      - name: Set Up Hyperledger Fabric Network
        working-directory: back-end/hyperledger-service/test-network
        run: |
          chmod +x network.sh organizations/ccp-generate.sh
          export PATH=${FABRIC_BIN_PATH}:$PATH
          ./network.sh up createChannel -c seedtransectionchannel -ca
          ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-typescript/ -ccl typescript
          ./organizations/ccp-generate.sh

      # Step 6: Start Hyperledger REST Service
      - name: Start Hyperledger REST Service
        working-directory: back-end/hyperledger-service/asset-transfer-basic/rest-api-typescript
        run: |
          export REDIS_PASSWORD=$(uuidgen)
          npm run start:redis
          npm run start:dev &
          sleep 30

      # Step 7: Run Hyperledger Tests
      - name: Run Hyperledger Tests
        working-directory: back-end/hyperledger-service/asset-transfer-basic/rest-api-typescript
        run: |
          npm test > test-results.txt 2>&1

      # Step 8: Teardown Hyperledger Fabric Network
      - name: Teardown Hyperledger Fabric Network
        working-directory: back-end/hyperledger-service/test-network
        run: |
          ./network.sh down
